version: "3.9"

services:

  technews-service:
    build: .
    container_name: technews-service
    restart: unless-stopped
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    env_file:
      - .env
    volumes:
      - .:/app
      - static_dev:/app/static
      - media_dev:/app/media
    ports:
      - "8000:8000"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  static_dev:
  media_dev:
